name: Lint and Comment

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  lint-and-comment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get lines of files changed
        id: get_lines
        run: |
          git diff --unified=0 HEAD^..HEAD | perl -ne 'BEGIN { my %h; } if (/^diff --git a\/(.*) b\/.*/) { $f=$1; } elsif (/^\@\@ -\d+(,\d+)? \+(\d+)(,(\d+))? \@\@/) { $o=$2; $n=$4; for ($i = 0; $i < $n; $i++) { $h{$f}->{int($o)}++; $o++; } } END { use JSON; my %result; while (my ($k, $v) = each %h) { my @lines = sort {$a <=> $b} map { int($_) } keys %$v; $result{$k} = \@lines; } print encode_json \%result; }' > changed_files.json

      - name: Run lint check
        shell: bash
        run: |
          IFS=' ' read -r -a files <<< "$(echo $(jq -r 'keys[]' <<< cat changed_files.json))"
          touch lint_files.txt
          for file in "${files[@]}"; do
            if [[ "$file" == *.js ]]; then
              lint_file=$(basename -- "$file" | sed 's/\.[^.]*$//').txt
              echo "$lint_file $(wc -l $file)" >> lint_files.txt
              # Replace the following line with your JavaScript linter
              cp $VALIDATION_PATH/js/* .
              NODE_PATH=/home/github/.npm-global/lib/node_modules ESLINT_USE_FLAT_CONFIG=true npx eslint -f ./formatter.js "$file" > $lint_file || true
            elif [[ "$file" == *.py ]]; then
              # Replace the following line with your Python linter
              flake8 "$file" > lint-result.txt || true
            fi
          done

      - name: Add comments to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.VALIDATION_PATH}/script.js`);
            script(github, context);
